/** One clear English sentence-group per doha-unit, split across verse blocks. */
export const groupEn = [
  `I bow to Ram — peaceful, eternal, sinless, giver of nirvana’s peace, served by Brahma, Shiva and Shesha, known through Vedanta, the Lord called Rama who took a human form through Maya. | O Raghu-lord, You are the inner Self of all: grant me steadfast bhakti and a mind free of desire. | I bow to the Wind’s son — golden as a mountain, fire to the demon-forest, first among the wise, ocean of virtues, beloved devotee of Raghuati. | Jamavant’s words pleased Hanuman’s heart. “Bear hunger on roots and fruit, brothers, until I return.” | “When I have seen Sita the work will be done, and my joy will be great.” He bowed to all and left, holding Raghunath in the heart. | On a fair hill by the sea He leapt in sport. Remembering Raghuvir again and again, the Wind’s son sprang with mighty force. | The mountain that received His foot sank toward Patal. He flew like Ram’s unfailing arrow. | The ocean, knowing Him Ram’s messenger, sent Mainak: “Become a resting-place.” | Hanuman touched the peak, bowed, and said: without Ram’s work, where is rest for me?`,

  `The gods saw the Wind’s son going, and wished to test His strength and wit. | They sent Surasa, mother of serpents. She said, “Today the gods have given me food.” | The Wind’s son answered: “Let me finish Ram’s work and tell the Lord news of Sita; then I will enter your mouth. That is truth — let me pass, Mother.” | She would not yield. “I will swallow you,” she said. He said, “Then swallow.” | She stretched her mouth a yojana; the monkey-form grew twice as wide. Sixteen yojanas, then thirty-two. | As she widened, He doubled. At a hundred yojanas He became minute, entered, and came out, then bowed for leave. | “I have seen why the gods sent you — the secret of your wit and strength.” She blessed Him: “You will do all of Ram’s work, O treasure of strength and wisdom,” and went. Hanuman went on glad.`,

  `A demoness lived in the sea who caught birds by their shadows on the water. | Whatever flew, she seized the shadow so it could not rise, and so she ate the creatures of the sky. | She tried the same deceit on Hanuman. The monkey knew the trick at once. | The brave Wind’s son slew her and crossed the ocean, mind steady. | On the far shore He saw a lovely wood — bees drunk on honey, trees of fruit and flower, birds and deer that pleased the heart. | He climbed a great rock without fear. Uma: this is not the monkey’s own greatness — it is the Lord’s glory that even Time cannot swallow. | From the peak He saw Lanka, a fortress beyond telling, ocean on every side, golden walls blazing. | Golden ramparts, jewelled palaces, markets and fair streets, elephants, horses, infantry and chariots, and hosts of many-formed rakshasas no one can count. Gardens, lakes and wells shone; beauty there could steal a sage’s mind. Terrible warriors guarded every side. Tulsidas tells only a little: when Raghuvir’s arrow becomes their tirtha they will find the true end. | Seeing many guards the monkey thought: I will take a tiny form and enter the city by night.`,

  `Hanuman became the size of a mosquito and went toward Lanka remembering Nara-Hari. | A rakshasi named Lankini challenged Him: “Fool, you come despising me? Every thief here is my food.” | The great monkey struck once; she fell vomiting blood. She rose, joined her palms, and spoke in fear. | “When Brahma gave Ravan his boon, Brahma also left me a sign: when you are shaken by a monkey’s blow, know the rakshasas are finished. | Father, great is my merit — I have seen Ram’s messenger with my own eyes.” | Heaven and liberation weighed together cannot equal the joy of a moment’s satsang.`,

  `“Enter the city and do the whole work, holding the King of Kosala in the heart. For whom Ram glances with grace, poison becomes nectar, enemy becomes friend, ocean a hoof-print, fire cool, and Meru a grain of dust.” | Hanuman took a minute form and entered, remembering God. He searched palace after palace and saw countless warriors. | He went into Dashanan’s house — splendour beyond speech. He saw Ravan asleep, but Vaidehi was not there. | Then He saw a beautiful dwelling with a separate Hari-temple. | The house was marked with Ram’s weapons, beauty beyond telling. Seeing fresh tulsi groves the monkey-king rejoiced.`,

  `“Lanka is a nest of rakshasas — how would a good soul live here?” While He reasoned, Vibhishan awoke. | Vibhishan remembered “Ram Ram.” Hanuman’s heart leapt: He had found a sajjan. “I will make myself known to him; from a sadhu no work is harmed.” | In a brahmin’s form He spoke. Vibhishan rose, bowed, asked welfare, and said: “Tell your story. Are you one of Hari’s servants? My heart is full of love. Or are you Ram Himself, friend of the lowly, come to make me blessed?” | Then Hanuman told all of Ram’s katha and His own name. Both bodies thrilled; minds drowned in the remembrance of virtues.`,

  `“Hear, son of Wind, our state — like a tongue living among teeth. Will the Lord of the Solar line ever take me as orphaned and show grace? This tamasic body has little sadhana, and the mind does not yet rest on His lotus feet.” | “Now I have hope, Hanuman: without Hari’s grace saints are not met. If Raghuvir has favoured me, that is why you insisted on giving me darshan.” | “Hear Vibhishan, the Lord’s way: He always loves the servant. What high birth have I? A restless monkey, lacking in every way. Whoever takes my name at dawn finds no food that day.” | “Even so, friend, hear: Raghuvir showed grace to one so low.” Remembering those virtues, His eyes filled.`,

  `“Those who know such a Master and still forget Him — why should they not be miserable?” Speaking Ram’s virtues they found unsayable rest. | Vibhishan then told how Janaka’s daughter lived there. Hanuman said, “Brother, I wish to see Mother Janaki.” | Vibhishan explained the way. The Wind’s son took leave, resumed that tiny form, and went to the Ashoka grove where Sita stayed. | He bowed in the mind. The night-watches passed as she sat: thin body, a single braid of jata, repeating in the heart the line of Raghupati’s virtues. | Her eyes were on her own feet; her mind was lost in Ram’s lotus feet. The Wind’s son was struck with grief seeing Janaki so worn.`,

  `He hid among leaves and thought, “What now, brother?” That very hour Ravan came, with many women dressed for show. | The wicked one reasoned with Sita in every way — peace, gifts, fear and division. “Listen, fair and wise one: Mandodari and all my queens I will make your attendants. Look toward me once.” | Vaidehi held a blade of grass as a screen, remembering Avadh’s lord, and said: “Hear, ten-headed one: does a lotus bloom in a firefly’s light? Understand this, wretch — you have no idea of Raghuvir’s arrow.” | “Fool, you stole me from an empty hermitage. Shameless one, have you no shame?” | Hearing Himself called a firefly and Ram a sun, Ravan drew his sword in fury.`,

  `“Sita, you have insulted me. I will cut your head with this hard blade — or obey at once, or lose your life.” | “That arm dark and lovely as a garland of blue lotuses, thick as an elephant’s trunk — can your terrible sword even touch it? Hear my vow, wretch.” | “Chandrahas, take away this burning born of Raghupati’s separation. You are cool and sharp — cut the weight of my sorrow,” said Sita. | He rushed to strike; Mandodari reasoned with him. He called the rakshasis: “Terrify her in every way. If she does not yield in a month and a day, I will kill her with the sword.” | Dashkandhar went home. Here the host of pishachinis took ugly forms and showed Sita terror.`,

  `One rakshasi named Trijata was skilled in love of Ram’s feet and in discernment. She called them all and told a dream: “Serve Sita — that is your good.” | “In dream a monkey burned Lanka and slew the rakshasa army. The ten-headed one rode a donkey, naked, head shaved, twenty arms cut.” | “So he went south, and Lanka seemed to pass to Vibhishan. Raghuvir’s victory-cry circled the city; then the Lord sent for Sita. I cry this dream aloud — it will come true in four days.” | Hearing her, they all took fright and fell at Janaka’s daughter’s feet. | Then they scattered, and Sita’s mind sank: “When the month and day end, this vile rakshasa will kill me.”`,

  `Joining her palms Sita said to Trijata: “Mother, you are the companion of my sorrow. I will leave the body — make a way quickly. This separation I cannot bear.” | “Bring wood, build a pyre, and set the fire, Mother. Honour my love, wise one.” Who can hear words sharp as thorns? | Trijata clasped her feet and comforted her with the Lord’s glory. “Tonight you will find no fire, O princess,” she said, and went home. | Sita said, “Fate is against me. Fire will not come; the pain will not end. Embers show in the sky, yet not one star falls to earth. The moon is fire and still drops no flame — as if it knows me luckless.” | “Hear my prayer, Ashoka tree: be true to your name, take my grief. Your new leaves are like fire — give me flame, do not delay.” | Seeing Sita wild with separation, that moment was a kalpa for the monkey. | Then the monkey, thinking in the heart, dropped the ring. She seized it as if the Ashoka had given her a coal of fire.`,

  `Then she saw the lovely ring, marked with Ram’s name, most beautiful. She looked in wonder, knew it, and her heart mixed joy and grief. | “Who can conquer unconquerable Raghurai? Maya cannot fashion such a thing.” While Sita thought many thoughts, Hanuman spoke sweet words. | He began to tell Ramchandra’s virtues; hearing them, Sita’s sorrow fled. She listened with ear and mind; He told the whole katha from the beginning. | “The story that is nectar to the ear — why does its teller not appear?” Then Hanuman came near. She sat back in amazement. | “Mother Janaki, I am Ram’s messenger — truth upon the Abode of compassion. This ring I brought; Ram gave it you as a token.” | “How did man and monkey join?” He told how that friendship was born. | Hearing the monkey’s loving words, trust rose. She knew in mind, deed and speech: this is the servant of the Ocean of grace.`,

  `Knowing Him Hari’s own, her love grew deep; eyes filled, horripilation spread. “Drowning in the sea of separation, Hanuman, you became my boat.” | “Now tell of welfare — I offer myself — of the younger brother and of Khara’s foe, the home of joy. Why has tender, gracious Raghurai put on hardness?” | “It is His nature to give servants joy. Does Raghunayak ever remember me? Will these eyes ever cool, Father, seeing that dark soft body?” Words would not come; eyes were full. “Ah Lord, I am utterly forgotten.” | Seeing Sita wild with pain, the monkey spoke soft humble words: “Mother, the Lord and His younger brother are well. The Abode of grace is sad in your sadness. Do not feel small in your heart — Ram’s love for you is double.” | “Now hear Raghuati’s message, Mother — take courage.” Saying this the monkey’s voice broke and His eyes filled.`,

  `“Ram said: Sita, in your separation everything has turned against me. New leaves feel like fire; night is death’s night; moon and sun burn. Lotus-beds are like spears; clouds rain as if boiling oil.” | “Those who were friends now give pain. The threefold breeze is like a serpent’s breath. If I told it, the pain would lessen a little — but whom can I tell? No one knows this.” | “The essence of our love, beloved, my mind alone knows — and that mind always stays with you. Know the taste of love in just this much.” Hearing the Lord’s message Vaidehi was lost in love, unaware of the body. | The monkey said, “Hold courage in the heart, Mother. Remember Ram, giver of joy to servants. Take Raghupati’s majesty into the chest; hearing me, drop this faintness.” | “The rakshasa hosts are moths, Raghuati’s arrows the fire. Mother, hold your heart steady — know the night-rovers already burned.”`,

  `“Had Raghuvir known, He would not have delayed. When Ram’s arrow-sun rises, Janaki, the darkness of the rakshasa host will vanish.” | “I would take you now, Mother — but I have not the Lord’s command, by Ram’s name. Hold on a few days; Raghuvir will come with the monkeys, slay the rakshasas, and take you. Narad and the three worlds will sing that fame.” | “Are all the monkey-sons equal to you? The rakshasas are mighty warriors. I have great doubt in my heart.” Hearing this He showed His true body — golden, mountain-like, terrible in war, a hero of vast strength. | Then Sita’s mind took trust. The Wind’s son became small again. | “Hear, Mother: a branch-animal has no great strength or wit. By the Lord’s glory a tiny snake can swallow Garuda.”`,

  `Hearing the monkey’s words mixed with bhakti, glory, blaze and strength, her mind was content. Knowing Him dear to Ram she blessed: “Be a treasure of strength and character, child.” | “Be ageless, deathless, a store of virtues, son. May Raghunayak show you much grace.” Hearing “May the Lord show grace,” Hanuman drowned in love. | Again and again He laid His head at her feet. Joining palms the monkey said: “Now I am fulfilled, Mother. Your blessing is famed as unfailing.” | “Hear, Mother, I am very hungry, seeing these fair fruits and trees.” “Hear, son, fierce night-rovers guard this wood.” “Mother, I do not fear them — if it pleases your heart.” | Seeing the monkey skilled in wit and strength, Janaki said, “Go. Holding Raghupati’s feet in the heart, child, eat the sweet fruit.”`,

  `He bowed and entered the garden. He ate fruit and began tearing trees. Many warrior-guards were there — some He killed, some fled shouting. | “Lord, a huge monkey has come and wrecked Ashoka Vatika. He ate fruit, uprooted trees, and crushed the watchmen into the earth.” | Ravan sent many warriors. Seeing them Hanuman roared and destroyed the night-rovers; a few half-dead ran crying. | Then he sent Akshayakumar, who went with countless champions. Seeing him come, Hanuman seized a tree, threatened him, struck him down, and thundered. | Some He killed, some crushed, some rubbed in dust; some fled crying, “Lord, the monkey’s strength is immense.”`,

  `Hearing of his son’s death, the lord of Lanka burned with rage and sent mighty Meghnad. “Do not kill him, son — bind him. Let us see where this monkey has his limit.” | Indrajit, peerless warrior, went, wrath born of a brother’s death. The monkey saw a terrible fighter coming, gnashed, roared and charged. | He tore up a vast tree and unhorsed Lanka’s prince. The great warriors with him the monkey seized and crushed against His own body. | Felling them He fought Indrajit — two like king-elephants. A fist-blow, then He climbed a tree; for a moment Indrajit fainted. Rising he worked much Maya; the Wind’s son could not be beaten. | He fitted the Brahmastra. The monkey thought: if I do not honour the Brahma-shaft, its boundless glory will be dimmed.`,

  `He struck the monkey with the Brahma-arrow. Even as it flew, Hanuman destroyed the army. Seeing the monkey fainted, Indrajit bound Him in nagpash and took Him away. | Uma: they whose Name the wise repeat to cut the bonds of becoming — could that One’s messenger truly come under a bond? For the Lord’s work the monkey let Himself be bound. | Hearing the monkey was bound, rakshasas ran; the whole court came for the spectacle. Entering Dashamukha’s assembly Hanuman saw a majesty beyond speech. | Gods and direction-guardians stood humble, palms joined; a glance of the brow made all afraid. Seeing that glory the monkey’s mind had no fear — as Garuda among serpents. | Dashanan looked at the monkey, laughed and spoke insult. Then remembering his son’s death, grief rose in the heart.`,

  `“Who are you, monkey? By whose strength did you ruin the garden? Have you not heard of me with your ears? I see you utterly without fear, fool.” | “For what crime did you kill rakshasas? Tell me, wretch — do you not care for your life?” “Hear, Ravan: He whose strength builds the host of universes, whose Maya is this creation —” | “By whose strength Brahma, Hari and Isha create, keep and destroy; on whose strength the thousand-headed one holds the egg of worlds with mountains and forests; who takes many bodies to save the gods — that Teacher of fools like you broke Hara’s hard bow and crushed the pride of kings with it. He slew Khara, Dushan, Trishira and Bali, all of matchless might.” | “I am the messenger of Him whose least strength conquered all moving and unmoving beings — Him whose dear wife you have stolen.”`,

  `“I know your greatness: you fought Sahasrabahu; in battle with Bali you won fame.” Hearing the monkey, Ravan laughed and made light of it. | “I ate fruit because I was hungry for the Lord’s sake. From monkey-nature I broke the trees. The body is dear to all, Master; those who walk the crooked path struck me. Whom they struck, I struck. On top of that your son bound me.” | “I am not ashamed of being bound. I wish to do my Lord’s work. I pray with joined palms, Ravan: drop pride and hear my teaching. Look to your own line. Leave delusion; worship the Remover of devotees’ fear.” | “Do not make enmity with Him whom even Time fears, who eats gods, asuras, moving and unmoving. Give Janaki back at my word.” | “Raghunayak is protector of those who bow, ocean of compassion, foe of Khara. If you go to refuge the Lord will keep you, forgetting your offence.”`,

  `“Hold Ram’s lotus feet in the heart; you will rule Lanka unshaken. Do not become a stain on the spotless moon of Pulastya’s fame. Speech without Ram’s name does not shine — think, drop pride and delusion.” | “A noble woman does not shine without cloth, though covered in jewels. Wealth and lordship turned from Ram go as if never gained — like rivers without living springs that dry when the rain has passed.” | “Hear, ten-necked one, I vow: for one turned from Ram there is no protector. A thousand Shankaras, Vishnus and Brahmas cannot save Ram’s enemy.” | “Drop this pride, root of delusion, giver of many thorns. Worship Ram, Raghunayak, the Lord, ocean of grace.”`,

  `Though the monkey spoke words soaked in bhakti, discernment, detachment and right policy, the hugely proud one laughed: “A very wise guru of a monkey has come to us.” | “Death is near you, wretch. You, low one, have begun to teach me.” “It will be the reverse,” said Hanuman. “I see your mind is clearly confused.” | Hearing the monkey he burned with rage. “Why do you not take this fool’s life at once?” The rakshasas rushed to kill; Vibhishan came with the ministers. | Bowing much he said: “A messenger should not be killed against niti. Give some other punishment, Gosain.” All said, “The counsel is good, brother.” Dashkandhar laughed: “Maim the monkey and send him back.” | “I tell you all plainly: the monkey’s affection is in the tail. Soak cloth in oil, bind it, then set it alight.”`,

  `“The tailless monkey will go there; then the fool will bring his master. I have seen the greatness of those he praised so much.” Hearing this the monkey smiled within: “Saraswati has become my help.” | The rakshasas heard Ravan and, fools, began that very work. The city had no cloth, ghee or oil left; the tail grew and the monkey made a game of it. | Citizens came for the show, kicked Him and laughed much. Drums beat, all clapped; they paraded Him through the city, then lit the tail. | Seeing the fire burn, Hanuman at once became extremely small, slipped free, and climbed the golden terraces. Rakshasa women were terrified. | That hour, urged by Hari, the forty-nine winds rose. The monkey laughed a great laugh, roared, grew, and touched the sky.`,

  `His body vast yet supremely swift, He ran from mansion to mansion. The city burned; people wailed. Crores of fierce flames leapt. | “Father! Mother!” — such cries were heard. “Who will save us now? We said this was no mere monkey — some god in vanar form. This is the fruit of insulting a sadhu: the city burns as if orphaned.” | He burned the city in the blink of an eye — except Vibhishan’s house. Shesha who bears the earth, Girija: the messenger of Him who made fire was not burned, for that reason. | He turned and turned and burned all Lanka, then leapt into the sea. | He quenched the tail, shed fatigue, took a small form again, and stood before Janaka’s daughter with joined palms.`,

  `“Mother, give me some token, as Raghunayak gave me.” Then she took off the chudamani; the Wind’s son received it with joy. | “Child, say this is my pranam. The Lord is complete in every way. Remembering His vow as friend of the lowly, O Master, take away this heavy distress.” | “Tell the tale of Indra’s son, and explain to the Lord the glory of His arrows. If the Lord does not come in a month and a day, He will not find me alive.” | “Tell me, monkey, how shall I keep my life? You too, child, are leaving, I know. Seeing you my breast grew cool — now for me it is the same day and the same night again.” | Comforting Janaka’s daughter and giving courage in many ways, the monkey bowed His head to her lotus feet and went toward Ram.`,

  `Leaving He roared a great roar; rakshasa women miscarried at the sound. He crossed the sea to this shore and gave the monkeys a whoop. | All rejoiced seeing Hanuman; the monkeys felt they had been born anew. Face glad, body shining with blaze — He had done Ramchandra’s work. | All met, utterly happy, like gasping fish finding water. They went glad toward Raghunayak, asking and telling the new history. | Then they all entered Madhuvan and, with Angad’s leave, ate honey-fruit. When the guards forbade them, fist-blows made them flee. | They ran and cried, “The Yuvaraj has wrecked the wood.” Hearing this Sugriva rejoiced: the monkeys have done the Lord’s work.`,

  `“If they had not found news of Sita, could they eat Madhuvan’s fruit?” So the king reasoned. Then the monkeys arrived with their host. | All came and bowed their heads to his feet. The monkey-lord met them with great love, asked welfare: “Welfare is seeing these feet. By Ram’s grace the work is especially done. Lord, Hanuman has done the work and saved all the monkeys’ lives.” | Hearing this Sugriva met Him again; then with the monkeys he went to Raghupati. When Ram saw the monkeys coming, His heart greatly rejoiced that the work was done. | The two brothers sat on a crystal rock. All the monkeys fell at their feet. | Raghuati, bundle of compassion, met them all with love. “Ask of welfare, Lord — now welfare is seeing these lotus feet.”`,

  `Jamavant said, “Hear, Raghuraya: on whom You set Your mercy, for him auspicious welfare is constant. Gods, men and sages are pleased with him. He is victorious, humble, an ocean of virtue; his fair fame lights the three worlds.” | “By the Lord’s grace all the work is done. Today our birth has borne fruit. Lord, what the Wind’s son has done cannot be told with a thousand mouths.” | Jamavant told Raghupati the Wind-son’s lovely deeds. The Treasure of compassion was greatly pleased at heart, then joyfully clasped Hanuman to His chest. | “Tell, child, how Janaki lives, how she keeps the watch over her own life.” | “Your Name is the sentry day and night; meditation on You the door-bar. Her eyes are locked on her own feet — by what path would the life-breath leave?”`,

  `“As I left she gave the chudamani.” Raghupati pressed it to His heart and took it. “Lord, her two eyes full of water, Janaka’s daughter said some words.” | “‘With the younger brother, Lord, take my head to Your feet. Friend of the lowly, remover of those who bow in pain: in mind, deed and word I love Your feet. For what offence, Lord, have I been abandoned?’” | “‘I admit one fault of mine: when we parted, the life-breath did not depart. Lord, that is the eyes’ crime — they stubbornly blocked the breath from leaving.’” | “‘The fire of separation, the cotton of the body, the wind of the breath — the body would burn in a moment. The eyes pour water for their own good, so the body cannot burn in that fire.’ Sita’s calamity is vast; even without telling, it is well known to You, O merciful to the poor.” | “Each blink, O Treasure of compassion, passes for her like a kalpa. Go quickly, Lord; bring her, conquering the wicked host with the strength of Your arms.”`,

  `Hearing Sita’s sorrow, the Lord who is the home of joy — His lotus eyes filled. “The one whose refuge I am in word, body and mind — can she be thought to be in distress even in a dream?” | Hanuman said, “Distress, Lord, is only when there is no remembrance and worship of You. What is this talk of rakshasas? Defeat the foe and bring Janaki.” | “Hear, monkey: none among gods, men or sages in a body is your equal in help. How can I repay you? My mind cannot even face the debt. Hear, son, I am not free of this obligation — I have thought it in the mind.” | Again and again the saviour of gods looked at the monkey; eyes water, body thrilling. | Hearing the Lord’s words, seeing His face, Hanuman’s body rejoiced. Overwhelmed with love He fell at the feet: “Save, save, O Blessed One.”`,

  `Again and again the Lord wished to lift Him; lost in love, He did not wish to rise. The Lord’s lotus hand on the monkey’s head — remembering that state, Gauri’s Lord was absorbed. Then Shiva, making the mind attentive, began to tell the most beautiful katha. | The Lord lifted the monkey and clasped Him to the heart, took His hand and seated Him very near. “Tell, monkey: Lanka kept by Ravan — how did you burn that most crooked fort?” | Hanuman knew the Lord was pleased and spoke without pride: “The great manhood of a branch-animal is to go from branch to branch. Crossing the sea, burning the golden city, wrecking the Creator’s rakshasa-wood — all that, Raghurai, is Your glory. Lord, none of it is my greatness.” | “Nothing is hard for him on whom You are favourable, Lord. By Your power even a wisp can burn a great fire.”`,

  `“Lord, bhakti is the greatest giver of joy. Give me, by grace, that devotion which does not leave.” Hearing the monkey’s supremely simple words, “So be it,” He said then, Bhavani. | Uma: he who has known Ram’s nature wants no other mood but worship. In whose heart this dialogue enters, he obtains bhakti to Raghupati’s feet. Hearing the Lord, the monkey-host cried, “Victory, victory, victory to the Compassionate, root of joy.” | Then Raghupati called the monkey-lord: “Make ready; let us go. Why delay now? Give the monkeys the order at once.” Seeing the sport, the gods rained many flowers and went glad from sky to their homes. | The monkey-king quickly called; troop-leaders came with troops — vanars and bears of many colours, matchless in strength.`,

  `They bowed their heads to the Lord’s lotus feet; bears and mighty monkeys roared. Ram looked on the whole monkey army, glancing with lotus eyes in grace. | Gaining the strength of Ram’s grace, the monkey-lords became as if winged kings of mountains. Then Ram set forth glad; many fair auspicious omens occurred. | He whose fame is all-auspicious — His setting out with omens is the right niti. Vaidehi knew the Lord had set out: the left limbs quivered as if to tell her. Whatever omen came to Janaki became inauspicious for Ravan. | Who can describe that marching host? Countless vanars and bears roared, nails as weapons, carrying peaks and trees, going at will on sky and earth. They roared like lions; the elephants of the quarters staggered and trumpeted. | The quarter-elephants trumpeted, earth shook, peaks swayed, the sea surged. Gandharvas, gods, sages, nagas and kinnaras were glad; sorrow left them. Crores of fierce monkey-warriors ran, singing the virtues of mighty Kosala’s lord. The generous serpent-king could not bear the weight and swooned again and again. He caught the tortoise’s hard shell in his teeth — how could that be comfortable? Knowing Raghuvir’s lovely departure, it was as if serpent-king on tortoise-shell were writing an unmoving holy verse. | In this way the Treasure of compassion went and camped on the ocean’s shore. Here and there the bears and many monkey-heroes began to eat fruit.`,

  `There the rakshasas lived in fear since the monkey burned Lanka. In their houses all thought: there is no saving the rakshasa line. “He whose messenger’s strength cannot be told — what good when He Himself comes to the city?” | Hearing the citizens from spies, Mandodari was even more distressed. In private she clasped her husband’s feet and spoke words soaked in niti: “Beloved, drop this quarrel with Hari. Hold my words as great good in the heart.” | “Remembering whose messenger’s deeds, rakshasa women miscarry on the earth — call His wife and your own ministers, and send her back, beloved, if you wish welfare. She has come as a frost-night on the lotus-grove of your line.” | “Hear, Nath: without giving Sita, Shambhu and Brahma themselves cannot make your good.” | “Ram’s arrows are like snakes, the rakshasa host like frogs. Before they are swallowed, drop stubbornness and make a way.”`,

  `The fool heard her words with his ears and laughed, world-famous in pride. “A woman’s nature is fearful, true. In the midst of blessing her mind is very weak with fear. If a monkey-army comes, the rakshasas will eat them for sport.” | “He whose fear makes the world-guardians tremble — that his wife is afraid is a great joke.” So saying he laughed and clasped her to his chest, and went to court with much fondness. Mandodari’s heart was anxious: fate has turned against my beloved. | He sat in court and received this news: the whole army has come across the sea. He asked the ministers, “Speak the fit counsel.” They all laughed: “Keep silent and stay. You conquered gods and asuras without fatigue — in what account are men and monkeys?” | If minister, physician and guru all three speak pleasant words from fear or hope, religion, body and kingdom — these three — quickly perish.`,

  `That very help gathered for Ravan: they sang praises again and again. Knowing the hour, Vibhishan came, bowed his head to his brother’s feet, then sat on his own seat and, receiving leave, spoke. | “If the Gracious One has asked me, I speak welfare according to my understanding, Father. Whoever wants his own good, fair fame, right mind, a fair end and many joys —” | “that man, Gosain, should leave another’s wife as one leaves the fourth-day moon. Even if one were lord of the fourteen worlds, enmity with beings will not let him stand. A cultured man who is an ocean of virtue — if he has a little greed, no one calls him good.” | “Desire, anger, pride, greed — Nath, all are paths to hell. Leaving them all, worship Raghuvir, whom the saints worship.”`,

  `“Father, Ram is no mere human king. He is Lord of worlds, Time of Time. Brahman, stainless, unborn, Bhagavan — pervasive, unconquered, beginningless, endless. For the good of cows, brahmins, the earth and gods, the Ocean of compassion has taken a human body.” | “Delighter of devotees, breaker of the wicked host, protector of Veda and dharma — hear, brother. Drop enmity with Him; bow the head. Raghunaath breaks the pain of those who take refuge.” | “Give Vaidehi to the Lord, Nath. Worship Ram, who loves without cause. The Lord does not abandon even one who has come to refuge stained with the sin of harming the world. He whose Name destroys the three fires — understand in the heart, Ravan: that Lord has appeared.” | “Again and again I clasp your feet and pray, ten-headed one: leave pride, delusion and conceit; worship the Lord of Kosala.” | “Muni Pulastya sent this word through his disciple. I have told it to you at once, Father, finding a fair hour.”`,

  `Malyavan, a most wise minister, heard this and was very glad. “Father, your younger brother is the ornament of niti. Hold in the heart what Vibhishan says.” | “These two fools speak the enemy’s increase. Is there no one here to drive them off?” Malyavan went home. Vibhishan spoke again with joined palms: “Right mind and crooked mind live in everyone’s chest, Nath — so say Purana and Veda.” | “Where there is right mind, there are many prosperities. Where there is crooked mind, calamity is the end. In your heart a reversed crooked mind has settled: you take harm as good and the enemy as dear. Sita is the death-night of the rakshasa line, and for her your love is thick.” | “Father, clasping your feet I ask: keep my affection. Give Sita to Ram; no harm will be yours.”`,

  `Vibhishan spoke the word agreed by the wise, Puranas and Shruti, unfolding niti. Hearing it Dashanan rose in rage: “Wretch, death has now come near you.” | “Fool, you have always lived on my living. The enemy’s side has pleased you, idiot. Tell me, wretch, who in the world is there whom I have not conquered by the strength of my arms?” | “Living in my city you love ascetics. Fool, go join them and teach them niti.” So saying he struck with his foot. The younger brother clasped the feet again and again. Uma: this is the greatness of a saint — even while being wronged he does good. | “You have struck me like a father — that is well. Worship Ram: that is your good, Nath.” Taking the ministers he went by the sky-path, and so all heard him say: | “Ram is the Lord of true resolve; your court is in Time’s power. I now go to Raghuvir’s refuge — do not blame me.”`,

  `When Vibhishan left speaking thus, all became as if life-spanless. Uma: insult to a sadhu at once harms the welfare of the whole. When Ravan abandoned Vibhishan he became luckless, without glory, that very instant. | He went glad toward Raghunayak, making many wishes in the mind: “I shall go and see those lotus feet, ruddy, soft, givers of joy to servants — the feet whose touch saved the sage’s wife and made Dandaka forest holy.” | “The feet Janaka’s daughter pressed to her heart, that ran with the deceitful deer; the feet that are lotuses in Hara’s lake-like heart — ah, blessed am I, I shall see those.” | “The feet whose sandals Bharat held with his mind fixed — those feet I shall behold today with these very eyes.”`,

  `Thinking thus with love he came at once to this side of the sea. The monkeys saw Vibhishan coming and took him for some special enemy-spy. | They held him and went to the monkey-lord and told all the news. Sugriva said, “Hear, Raghurai: Dashanan’s brother has come to meet you.” | The Lord said, “Friend, what do you think?” The monkey-lord said, “Hear, lord of men: a rakshasa’s Maya cannot be known. Why has this shape-changer come? The fool has come to take our secret. Bind and keep him — that is my mind.” | “Friend, you have thought niti well. My vow is to remove the fear of one who has come to refuge.” Hearing the Lord, Hanuman rejoiced: the Blessed One is tender to those who come for shelter. | “Those who abandon one come to refuge, guessing their own harm — those men are wretched and full of sin; even looking at them is loss.”`,

  `“Even if crores of brahmin-killings cling to him — if he has come to refuge I do not abandon him. The moment a being turns his face to me, the sins of crores of births perish then.” | “A sinner’s native nature is that my worship never pleases him. If he were truly evil-hearted, would he come before me? The devotee of clean mind attains me. Deceit, trick and fault-finding do not please me.” | “Even if Dashashirsha sent him to spy, still there is no fear or loss, monkey-lord. All the rakshasas in the world, friend — Lakshman can slay them in a blink. If he has come afraid to refuge, I will keep him like my own life.” | Smiling, the Abode of compassion said, “Bring him either way.” Crying “Victory to the Gracious,” Angad went with Hanuman.`,

  `The monkeys courteously put him in front and went where Raghupati, mine of compassion, was. From afar he saw the two brothers, givers of the gift of joy to the eyes. | Then looking on Ram, the abode of beauty, he stood stunned, one-pointed, blink held. Long arms, lotus-red eyes, dark limbs, remover of those who bow in fear. Lion-shoulders, a broad chest shining; the face stole countless Madana-minds. | Eyes water, body utterly thrilling. Steadying the mind he spoke softly: “Nath, I am Dashanan’s brother, born in the rakshasa line, O saviour of gods. Sin is naturally dear to this tamasic body, as an owl loves the dark.” | “Hearing fair fame with my ears I have come, Lord, breaker of the fear of becoming. Save, save, remover of pain, Raghuvir, joy of refuge.”`,

  `Seeing him make dandavat, the Lord rose at once in special joy. The humble words pleased the Lord’s mind. With vast arms He clasped him to the heart, met him with the younger brother, seated him near, and spoke words that remove a devotee’s fear. | “Tell, lord of Lanka, with your family: how is welfare, living in that wrong place? You dwell day and night in a circle of the wicked. Friend, how does dharma hold up? I know all your ways: you are most skilled in niti; injustice does not please you.” | “Better even a stay in hell, Father, than that the Creator give the company of the wicked. Now, seeing these feet, there is welfare, Raghuraya — since You knew me as Your own and showed mercy.” | “There is no welfare for a being, nor rest of mind even in dream, until he worships Ram, leaving the home of sorrow and desire.”`,

  `“Until then many wicked things live in the heart — greed, delusion, envy, pride, conceit — until Raghunaath dwells in the chest, bow in hand, arrows at the waist. The young darkness of I-and-mine is a night that pleases the owls of attachment and hate.” | “They live in the being’s mind until the sun of the Lord’s glory is not there. Now I am well; great fears are gone, seeing Your lotus feet, Ram. On whom You, the Gracious, are favourable, the three fires of becoming do not touch him.” | “I am a rakshasa of most low nature; I never did an auspicious act. The Lord whose form does not come even in sages’ meditation — that Lord has gladly clasped me to the heart.” | “Ah, my fortune is boundless — Ram, bundle of grace and joy. With my eyes I have seen the pair of lotus feet served by Brahma and Shiva.”`,

  `“Hear, friend, I tell my own nature — known to Bhusundi, Shambhu and Girija. If a man is foe to all moving and unmoving, and comes afraid to my refuge, leaving pride, delusion, deceit and many tricks — I at once make him equal to a sadhu.” | “Mother, father, brother, son, wife, body, wealth, house, friends and family — gathering the threads of affection for all, he binds the mind to my feet with a strong cord. Seeing all alike, wanting nothing, with neither joy nor grief nor fear in the mind —” | “such a sajjan dwells in my heart as wealth dwells in a greedy man’s heart. Saints like you are dear to me. I take a body for no other need.” | “Worshippers of the saguna who delight in others’ good, firm in niti and vow — those men are like my life, who have love for the feet of the twice-born.”`,

  `“Hear, lord of Lanka: all virtues are yours; therefore you are exceedingly dear to me.” Hearing Ram’s words the monkey-troops all cried, “Victory to the host of compassion.” | Hearing the Lord’s speech, Vibhishan was not sated, knowing it nectar to the ear. Again and again he held the lotus feet; the boundless love would not fit in the heart. “Hear, Deva, Lord of moving and unmoving, protector of those who bow, inner witness: some prior longing stayed in the chest — the river of love for the Lord’s feet has washed it away.” | “Now, Gracious One, give me Your purifying bhakti, forever dear to Shiva’s mind.” “So be it,” said the Lord, steadfast in war, and at once asked for ocean-water. “Though, friend, you have no such wish, my darshan in the world is never barren.” | So saying Ram marked his tilak. An endless rain of flowers fell from the sky. | Ravan’s wrath was fire, his own breath a fierce wind: burning Vibhishan He saved, and gave unbroken kingship.`,

  `The very wealth Shiva gave Ravan when he offered ten heads — that same fortune Raghunath gave Vibhishan, almost shyly. They who leave such a Lord to worship another are beasts without tail or horn. Knowing him His own, the Lord accepted him. The Lord’s nature pleased the monkey-clans’ minds. | Then the All-knowing, dweller in every heart, all forms yet without all, detached, spoke words that keep niti — the Man who is the cause, destroyer of the danava line: “Hear, monkey-lord and brave lord of Lanka: how shall we cross this deep ocean, crowded with crocodiles, serpents and fish-kinds, most unfathomable, hard to cross every way?” | The lord of Lanka said, “Hear, Raghunayak: Your arrow can dry crores of oceans. Even so, niti has sung this: go and make a humble request to the sea.” | “Lord, the ocean is Your family-guru; he will think and tell a way. Without effort the whole host of bears and monkeys will cross the sea.”`,

  `“Friend, you have spoken a good means. Let it be done if Heaven helps.” This counsel did not please Lakshman’s mind. Hearing Ram’s words he was very pained. “Nath, what trust is there in fate? Dry the ocean, making the mind wrathful. Fate is the one support of a coward’s mind; the lazy cry ‘fate, fate.’” | Hearing this Raghuvir smiled: “We shall do just so; hold the mind steady.” So saying the Lord explained to the younger brother and went near the ocean. First He bowed His head in pranam, then sat on the bank spreading darbha. | When Vibhishan had come to the Lord, Ravan sent spies behind. | They saw the whole conduct, wearing false monkey-bodies. In their hearts they praised the Lord’s virtues and His love for those who come to refuge.`,

  `Openly they began to tell Ram’s nature; in great love they forgot concealment. Then the monkeys knew they were the enemy’s messengers, bound them all and brought them to the monkey-lord. | Sugriva said, “Hear, all vanars: maim the rakshasas and send them back.” Hearing Sugriva the monkeys ran, bound them and paraded them around the camp. They began to beat them in many ways; though they cried piteously they were not left. | “By Kosala’s lord we swear — do not take our nose and ears.” Hearing this Lakshman called them near. Pity arose; he smiled and freed them at once. “Give this letter of Ravan. Read Lakshman’s words, O killer of your line.” | “Tell this generous message of mine to the fool to his face: give Sita and meet us; otherwise your Time has come.”`,

  `At once they bowed to Lakshman’s feet and went, telling the tale of virtues. Telling Ram’s glory they came to Lanka and bowed their heads to Ravan’s feet. | Dashanan laughed and asked news: “Shuka, why do you not tell your own welfare? Then tell news of Vibhishan, whom death has come very near. The fool left Lanka’s kingship; he will become a luckless insect of the hand.” | “Then tell of the bear-and-monkey army, driven by harsh Time, that has come — they whose life-guard has become the soft-hearted, simple ocean. Then tell of the ascetics in whose hearts my terror is great.” | “Did they meet, or turn back hearing my fair fame with their ears? Why do you not speak of the enemy host’s blaze and strength? Your mind is very shaken.”`,

  `“Nath, as you have asked in grace, so understand what is said, leaving wrath. When your younger brother went and met them, Ram marked his tilak that very instant.” | “Hearing we were Ravan’s messengers, the monkeys bound us and gave many pains. They began to cut ears and noses; they left us on Ram’s oath. You asked, Nath, of Ram’s army: a hundred crore mouths cannot tell it.” | “Bears and monkeys of many colours, fierce-faced, vast, terrible. He who burned the city and slew your son — among all the monkeys his strength is counted small. Numberless named warriors, hard and dreadful, with the strength of numberless nagas, vast.” | “Dvivida, Mayanda, Nila, Nala, Angad, Gada, Bikatasya, Dadhimukha, Keshari, Nisatha, Satha, Jamavant — heaps of strength.”`,

  `“These monkeys are all equal to Sugriva. Who can count crores like them? By Ram’s grace their strength is matchless; they count the three worlds as a blade of grass.” | “So I heard with my ears, Dashkandhar: there are eighteen padma of monkey troop-leaders. Nath, there is no monkey in the camp who could not conquer you in battle.” | “In great wrath they all rub their hands. They do not strike — they have not Raghunaath’s leave. They would dry the ocean with fish and serpents, or else fill it with great peaks; they would crush Dashashirsha into dust — such words all the monkeys speak. They roar and threaten, naturally without fear, as if they wish to swallow Lanka.” | “All the monkeys and bears are naturally brave, and on their heads is Lord Ram. They could conquer even crores of Ravan-Times in war.”`,

  `Ravan then asked his brother, skilled in niti, of Ram’s blaze, strength and vast wit. Hearing his words he went to the ocean, asking a path, compassion in the heart. | Hearing this the ten-headed one laughed: “If such is the mind, having made monkeys his help — he takes a naturally timid one’s word as firm and has begun this stubbornness with the sea. Fool, why this false praise? I have sounded the enemy’s strength and wit.” | “Whose minister is fearful Vibhishan — where in the world is victory and glory for him?” Hearing the wretch’s words the messenger’s anger grew. Thinking of the hour he drew out the letter. “Ram’s younger brother gave this letter. Nath, read it and cool your breast.” | Dashanan took it in the left hand, laughing, called ministers and began to read, the fool. | “Do not, fool, charm the mind with talk and destroy the remnant of your line. In enmity with Ram you will not be saved, though you take refuge with Vishnu, Brahma and Isha.” | “Or leave pride like your younger brother and become a bee at the Lord’s lotus feet — or, wretch, become a moth with your line in the fire of Ram’s arrows.”`,

  `Hearing, afraid in mind, he smiled with the mouth and said for all to hear: “Fallen on earth he grabs at the sky — this is the word-play of a petty ascetic.” Shuka said, “Nath, all these words are true. Understand, leaving your proud nature.” | “Hear my words, dropping wrath. Nath, leave opposition to Ram. Raghuvir’s nature is most tender, though He is King of all worlds. Meeting you the Lord will show grace; He will not hold even one offence in the heart. Give Janaka’s daughter to Raghunath. Do this much of my master’s word.” | When he said to give Vaidehi, the fool struck him with his foot. Bowing his head to the feet he went there — where Raghunayak, ocean of compassion, was. Making pranam he told his own story; by Ram’s grace he found his true state. By Agastya’s curse, Bhavani, the wise sage had become a rakshasa. Honouring Ram’s feet again and again, the sage set his step toward his own ashram. | The dull ocean accepted no prayer; three days passed. Then Ram spoke in wrath: without fear, love is not born.`,

  `“Lakshman, bring bow and arrow. I will dry the ocean with a fiery shaft. Prayer to a fool, love to the crooked, fair niti to the naturally miserly, a wisdom-tale to one sunk in I-and-mine, talk of detachment to the very greedy, calm to the angry, Hari-katha to the lustful — are like seed sown in barren ground.” | So saying Raghupati raised the bow. This counsel pleased Lakshman’s mind. The Lord fitted a terrible shaft; a blaze rose in the ocean’s heart. Crocodiles, serpents and fish-hosts panicked. When the sea-creatures knew they were burning, | in a brahmin’s form, leaving pride, the ocean came with a golden tray full of many jewels. | A plantain bears fruit only when cut, though one water it crore-fold. Hear, lord of birds: the low do not bow to prayer — only to a scolding.`,

  `Afraid, the ocean clasped the Lord’s feet: “Forgive, Nath, all my faults. Sky, wind, fire, water, earth — Nath, their doing is naturally inert. Urged by You, Maya produced them; all the books sing they are for creation. As the Lord’s command is for each, so he remains and finds joy.” | “The Lord has done well to teach me. The bounds too are Yours. Drum, rustic, shudra, beast and woman — all are fit for correction. By the Lord’s glory I will go dry; the army will cross — that will not be my greatness. The Lord’s order, the Vedas sing, cannot be appealed. I will do at once whatever pleases You.” | Hearing most humble words the Gracious One said, smiling: “Father, tell the means by which the monkey-army may cross.”`,

  `“Nath, the two monkey-brothers Nila and Nala received a sage’s blessing in childhood. Mountains they touch will float; by Your glory they will cross the sea. I too, holding Your majesty in the heart, will help with what strength I estimate. In this way, Nath, bind the ocean, so this fair fame is sung in the three worlds.” | “With this arrow slay the wicked sinful men who live on my northern shore.” Hearing the sea’s heart-pain, the Gracious One, Ram steadfast in war, at once removed it. Seeing Ram’s great strength and prowess the ocean was glad and happy. He told the Lord the whole conduct, bowed to the feet, and the sea departed. | The ocean went to his house; this counsel pleased Shri Raghupati. This deed, which steals Kali’s stain, Tulsidas the servant has sung as he could. O mind, leave all hope and trust; always sing and hear Raghuati’s virtues — home of joy, destroyer of doubt, queller of grief. | The singing of Raghunayak’s virtues gives all fair blessings. Those who hear with honour cross the ocean of becoming without a boat.`,
];
